# Generated by Django 4.2.7 on 2025-08-01 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='소속 기관')),
                ('bio', models.TextField(blank=True, verbose_name='소개')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='프로필 이미지')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='이메일 알림')),
                ('analysis_count', models.PositiveIntegerField(default=0, verbose_name='분석 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
                'db_table': 'user_profile',
            },
        ),
    ]
