# Generated by Django 4.2.7 on 2025-09-01 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100, unique=True, verbose_name='클래스명')),
                ('disease_name_ko', models.CharField(max_length=100, verbose_name='질병명 (한국어)')),
                ('disease_name_en', models.CharField(max_length=100, verbose_name='질병명 (영어)')),
                ('description', models.TextField(verbose_name='질병 설명')),
                ('symptoms', models.TextField(verbose_name='증상')),
                ('causes', models.TextField(verbose_name='원인')),
                ('treatment', models.TextField(verbose_name='치료법')),
                ('prevention', models.TextField(verbose_name='예방법')),
                ('default_severity', models.CharField(choices=[('mild', '경미'), ('moderate', '보통'), ('severe', '심각'), ('critical', '긴급')], default='moderate', max_length=20, verbose_name='기본 심각도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '질병 클래스',
                'verbose_name_plural': '질병 클래스들',
                'db_table': 'disease_classes',
                'ordering': ['class_name'],
            },
        ),
        migrations.CreateModel(
            name='FishAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='fish_analysis/original/%Y/%m/%d/', verbose_name='원본 이미지')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='fish_analysis/processed/%Y/%m/%d/', verbose_name='처리된 이미지')),
                ('status', models.CharField(choices=[('processing', '분석 중'), ('completed', '완료'), ('failed', '실패')], default='processing', max_length=20, verbose_name='분석 상태')),
                ('overall_health_status', models.CharField(blank=True, choices=[('good', '상'), ('fair', '중'), ('poor', '하')], max_length=10, null=True, verbose_name='전체 건강 상태')),
                ('yolo_confidence_avg', models.FloatField(blank=True, null=True, verbose_name='YOLO 평균 신뢰도')),
                ('total_detections', models.IntegerField(default=0, verbose_name='총 탐지 개수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '어류 분석',
                'verbose_name_plural': '어류 분석들',
                'db_table': 'fish_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bbox_x', models.FloatField(verbose_name='바운딩박스 X 좌표')),
                ('bbox_y', models.FloatField(verbose_name='바운딩박스 Y 좌표')),
                ('bbox_width', models.FloatField(verbose_name='바운딩박스 너비')),
                ('bbox_height', models.FloatField(verbose_name='바운딩박스 높이')),
                ('yolo_confidence', models.FloatField(verbose_name='YOLO 신뢰도')),
                ('cropped_image', models.ImageField(upload_to='fish_analysis/cropped/%Y/%m/%d/', verbose_name='크롭된 이미지')),
                ('disease_class', models.CharField(max_length=100, verbose_name='질병 클래스')),
                ('disease_name_ko', models.CharField(max_length=100, verbose_name='질병명 (한국어)')),
                ('vgg_confidence', models.FloatField(verbose_name='VGG 신뢰도')),
                ('severity', models.CharField(choices=[('mild', '경미'), ('moderate', '보통'), ('severe', '심각'), ('critical', '긴급')], max_length=20, verbose_name='심각도')),
                ('description', models.TextField(blank=True, null=True, verbose_name='질병 설명')),
                ('treatment_recommendation', models.TextField(blank=True, null=True, verbose_name='치료 권장사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='fish_analysis.fishanalysis', verbose_name='분석')),
            ],
            options={
                'verbose_name': '질병 탐지',
                'verbose_name_plural': '질병 탐지들',
                'db_table': 'disease_detections',
                'ordering': ['-vgg_confidence'],
            },
        ),
    ]
