# Generated by Django 4.2.7 on 2025-08-01 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fish_analysis.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='세션 이름')),
                ('description', models.TextField(blank=True, verbose_name='세션 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '분석 세션',
                'verbose_name_plural': '분석 세션들',
                'db_table': 'analysis_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField(verbose_name='좌상단 X')),
                ('y1', models.FloatField(verbose_name='좌상단 Y')),
                ('x2', models.FloatField(verbose_name='우하단 X')),
                ('y2', models.FloatField(verbose_name='우하단 Y')),
                ('confidence', models.FloatField(verbose_name='신뢰도')),
                ('class_name', models.CharField(max_length=50, verbose_name='클래스 이름')),
            ],
            options={
                'verbose_name': '탐지 박스',
                'verbose_name_plural': '탐지 박스들',
                'db_table': 'detection_box',
            },
        ),
        migrations.CreateModel(
            name='FishAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=fish_analysis.models.fish_image_upload_path, verbose_name='생선 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='분석 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('fish_detected', models.BooleanField(default=False, verbose_name='생선 탐지 여부')),
                ('fish_species', models.CharField(choices=[('flatfish', '광어(넙치)'), ('unknown', '알 수 없음')], default='unknown', max_length=20, verbose_name='생선 종류')),
                ('species_confidence', models.FloatField(default=0.0, verbose_name='종류 분류 신뢰도')),
                ('overall_health', models.CharField(choices=[('healthy', '건강함'), ('diseased', '질병 있음'), ('suspicious', '의심스러움'), ('unknown', '알 수 없음')], default='unknown', max_length=20, verbose_name='전체 건강 상태')),
                ('health_confidence', models.FloatField(default=0.0, verbose_name='건강 상태 신뢰도')),
                ('image_width', models.IntegerField(default=0, verbose_name='이미지 너비')),
                ('image_height', models.IntegerField(default=0, verbose_name='이미지 높이')),
                ('quality_score', models.FloatField(default=0.0, verbose_name='이미지 품질 점수')),
                ('processing_time', models.FloatField(default=0.0, verbose_name='처리 시간(초)')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='권장사항')),
                ('warning_messages', models.JSONField(blank=True, default=list, verbose_name='경고 메시지')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='fish_analysis.analysissession', verbose_name='분석 세션')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '생선 분석 결과',
                'verbose_name_plural': '생선 분석 결과들',
                'db_table': 'fish_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(choices=[('bacterial', '세균성 질병'), ('viral', '바이러스성 질병'), ('parasitic', '기생충성 질병'), ('fungal', '진균성 질병'), ('nutritional', '영양 결핍'), ('environmental', '환경적 요인'), ('unknown', '알 수 없음')], max_length=50, verbose_name='질병 유형')),
                ('confidence', models.FloatField(verbose_name='신뢰도')),
                ('severity', models.FloatField(verbose_name='심각도')),
                ('description', models.TextField(verbose_name='질병 설명')),
                ('treatment_recommendation', models.TextField(blank=True, verbose_name='치료 권장사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='탐지 시간')),
                ('affected_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish_analysis.detectionbox', verbose_name='영향받은 영역')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='fish_analysis.fishanalysis', verbose_name='분석 결과')),
            ],
            options={
                'verbose_name': '질병 탐지',
                'verbose_name_plural': '질병 탐지들',
                'db_table': 'disease_detection',
                'ordering': ['-confidence'],
            },
        ),
        migrations.AddField(
            model_name='detectionbox',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_boxes', to='fish_analysis.fishanalysis', verbose_name='분석 결과'),
        ),
    ]
