# Generated by Django 4.2.7 on 2025-08-25 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('inventory', '0001_initial'), ('inventory', '0002_inventory_ordered_quantity_and_more'), ('inventory', '0003_alter_inventory_stock_quantity'), ('inventory', '0004_inventorylog_anomaly_score_inventorylog_anomaly_type_and_more'), ('inventory', '0005_remove_inventorylog_batch_number_and_more'), ('inventory', '0006_inventory_reorder_point_and_more'), ('inventory', '0007_alter_inventorylog_total_amount_and_more'), ('inventory', '0008_inventory_total_amount_inventory_unit_price'), ('inventory', '0009_alter_inventorylog_source_type'), ('inventory', '0010_alter_inventory_ordered_quantity_and_more')]

    initial = True

    dependencies = [
        ('fish_registry', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='재고 수량')),
                ('unit', models.CharField(max_length=20, verbose_name='단위')),
                ('status', models.CharField(choices=[('registered', '등록됨'), ('normal', '정상'), ('low', '부족'), ('abnormal', '이상')], default='registered', max_length=20, verbose_name='상태')),
                ('aquarium_photo_path', models.TextField(blank=True, null=True, verbose_name='사진 경로')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_registry.fishtype', verbose_name='어종')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('ordered_quantity', models.IntegerField(default=0, verbose_name='주문 수량')),
                ('reorder_point', models.IntegerField(blank=True, null=True, verbose_name='재주문점')),
                ('safety_stock_quantity', models.IntegerField(blank=True, null=True, verbose_name='안전재고 수량')),
                ('total_amount', models.IntegerField(blank=True, null=True, verbose_name='총액')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='단가')),
            ],
            options={
                'verbose_name': '재고',
                'verbose_name_plural': '재고들',
                'db_table': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('order', '주문으로 인한 차감'), ('cancel', '주문 취소로 인한 복원'), ('adjustment', '재고 조정'), ('stock_in', '입고')], max_length=20, verbose_name='거래 유형')),
                ('quantity_change', models.FloatField(verbose_name='수량 변동 (음수: 차감, 양수: 증가)')),
                ('unit', models.CharField(max_length=20, verbose_name='단위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_registry.fishtype', verbose_name='어종')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='관련 재고')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='관련 주문')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '재고 거래',
                'verbose_name_plural': '재고 거래들',
                'db_table': 'stock_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('in', '입고'), ('out', '출고'), ('adjust', '조정')], max_length=10, verbose_name='입출고 구분')),
                ('change', models.IntegerField(verbose_name='수량 변화량')),
                ('before_quantity', models.IntegerField(verbose_name='이전 수량')),
                ('after_quantity', models.IntegerField(verbose_name='이후 수량')),
                ('unit', models.CharField(max_length=20, verbose_name='단위')),
                ('source_type', models.CharField(choices=[('manual', '수동'), ('AI', 'AI'), ('YOLO', 'YOLO'), ('order', '주문'), ('payment', '결제'), ('order_shipout', '주문 출고')], max_length=20, verbose_name='처리 방식')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_registry.fishtype', verbose_name='어종')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='재고')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('anomaly_score', models.FloatField(blank=True, default=1.0, null=True, verbose_name='이상 탐지 점수')),
                ('anomaly_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='이상 유형')),
                ('is_anomaly', models.BooleanField(blank=True, default=False, null=True, verbose_name='이상 탐지 여부')),
                ('total_amount', models.IntegerField(blank=True, null=True, verbose_name='총액')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='단가')),
            ],
            options={
                'verbose_name': '입출고 이력',
                'verbose_name_plural': '입출고 이력들',
                'db_table': 'inventory_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPattern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('seasonal', '계절성'), ('weekly', '주간'), ('daily', '일간'), ('trend', '트렌드'), ('anomaly', '이상 패턴')], max_length=50, verbose_name='패턴 유형')),
                ('pattern_data', models.JSONField(verbose_name='패턴 데이터')),
                ('confidence_interval', models.JSONField(blank=True, null=True, verbose_name='신뢰구간')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='마지막 업데이트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_registry.fishtype', verbose_name='어종')),
            ],
            options={
                'verbose_name': '재고 패턴',
                'verbose_name_plural': '재고 패턴들',
                'db_table': 'inventory_patterns',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAnomaly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(max_length=50, verbose_name='이상 유형')),
                ('severity', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('CRITICAL', '긴급')], max_length=20, verbose_name='심각도')),
                ('confidence_score', models.FloatField(verbose_name='AI 신뢰도')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='탐지 시각')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결 시각')),
                ('description', models.TextField(verbose_name='이상 상황 설명')),
                ('ai_model_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='AI 모델 버전')),
                ('features_used', models.JSONField(blank=True, null=True, verbose_name='사용된 특성들')),
                ('prediction_horizon', models.IntegerField(blank=True, null=True, verbose_name='예측 기간 (일)')),
                ('recommended_action', models.TextField(blank=True, null=True, verbose_name='권장 조치')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='재고')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorylog', verbose_name='관련 로그')),
            ],
            options={
                'verbose_name': '재고 이상 탐지',
                'verbose_name_plural': '재고 이상 탐지들',
                'db_table': 'inventory_anomalies',
                'ordering': ['-detected_at'],
            },
        ),
    ]
