# Generated by Django 4.2.7 on 2025-08-08 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fish_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.FloatField(default=0, verbose_name='재고 수량')),
                ('unit', models.CharField(max_length=20, verbose_name='단위')),
                ('status', models.CharField(choices=[('registered', '등록됨'), ('normal', '정상'), ('low', '부족'), ('abnormal', '이상')], default='registered', max_length=20, verbose_name='상태')),
                ('aquarium_photo_path', models.TextField(blank=True, null=True, verbose_name='사진 경로')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('fish_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fish_registry.fishtype', verbose_name='어종')),
            ],
            options={
                'verbose_name': '재고',
                'verbose_name_plural': '재고들',
                'db_table': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('in', '입고'), ('out', '출고')], max_length=10, verbose_name='입출고 구분')),
                ('change', models.FloatField(verbose_name='수량 변화량')),
                ('before_quantity', models.FloatField(verbose_name='이전 수량')),
                ('after_quantity', models.FloatField(verbose_name='이후 수량')),
                ('unit', models.CharField(max_length=20, verbose_name='단위')),
                ('source_type', models.CharField(choices=[('manual', '수동'), ('AI', 'AI'), ('YOLO', 'YOLO')], max_length=20, verbose_name='처리 방식')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_registry.fishtype', verbose_name='어종')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='재고')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '입출고 이력',
                'verbose_name_plural': '입출고 이력들',
                'db_table': 'inventory_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
