# Generated by Django 4.2.7 on 2025-08-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='ordered_quantity',
            field=models.FloatField(default=0, verbose_name='주문 수량'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_quantity',
            field=models.FloatField(default=0, verbose_name='등록 수량'),
        ),
    ]
