# Generated by Django 4.2.7 on 2025-08-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
