# Generated by Django 4.2.7 on 2025-08-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_ordered_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_quantity',
            field=models.FloatField(default=0, verbose_name='재고 수량'),
        ),
    ]
