# Generated by Django 4.2.7 on 2025-08-15 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish_registry', '0003_alter_fishtype_user'),
        ('order', '0005_order_has_stock_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alter_inventory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('order', '주문으로 인한 차감'), ('cancel', '주문 취소로 인한 복원'), ('adjustment', '재고 조정'), ('stock_in', '입고')], max_length=20, verbose_name='거래 유형')),
                ('quantity_change', models.FloatField(verbose_name='수량 변동 (음수: 차감, 양수: 증가)')),
                ('unit', models.CharField(max_length=20, verbose_name='단위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_registry.fishtype', verbose_name='어종')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='관련 재고')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='관련 주문')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '재고 거래',
                'verbose_name_plural': '재고 거래들',
                'db_table': 'stock_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
