# Generated by Django 4.2.7 on 2025-08-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=50)),
                ('aliases', models.JSONField(blank=True, null=True)),
                ('unit', models.CharField(default='kg', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0)),
                ('order_datetime', models.DateTimeField()),
                ('delivery_date', models.DateField()),
                ('source_type', models.CharField(choices=[('text', '문자'), ('voice', '음성'), ('image', '이미지')], max_length=10)),
                ('raw_input_path', models.TextField(blank=True, null=True)),
                ('transcribed_text', models.TextField(blank=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '등록됨'), ('paid', '결제 완료'), ('ready', '출고 준비'), ('delivered', '납품 완료'), ('cancelled', '취소됨')], default='pending', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.business')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.fishtype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
    ]
