# Generated by Django 4.2.7 on 2025-08-16 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='주문 ID')),
                ('business_id', models.IntegerField(verbose_name='거래처 ID')),
                ('total_price', models.IntegerField(default=0, verbose_name='총 주문 금액')),
                ('order_datetime', models.DateTimeField(auto_now_add=True, verbose_name='주문 등록 일시')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='주문 메모')),
                ('source_type', models.CharField(choices=[('manual', '수동'), ('voice', '음성'), ('text', '문자')], max_length=20, verbose_name='주문 방식')),
                ('raw_input_path', models.TextField(blank=True, null=True, verbose_name='원문 경로 (음성 mp3 또는 문자 원문)')),
                ('transcribed_text', models.TextField(blank=True, null=True, verbose_name='파싱된 텍스트')),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True, verbose_name='납기일')),
                ('ship_out_datetime', models.DateTimeField(blank=True, null=True, verbose_name='출고일')),
                ('order_status', models.CharField(choices=[('placed', '등록됨'), ('ready', '출고 준비'), ('delivered', '납품 완료'), ('cancelled', '취소됨')], default='placed', max_length=20, verbose_name='주문 상태')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='취소 사유')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='긴급 주문 여부')),
                ('has_stock_issues', models.BooleanField(default=False, verbose_name='재고 부족 여부')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문들',
                'db_table': 'orders',
                'ordering': ['-order_datetime'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='주문 품목 ID')),
                ('item_name_snapshot', models.TextField(blank=True, null=True, verbose_name='주문 당시 품목명 스냅샷')),
                ('quantity', models.FloatField(verbose_name='주문 수량 (소수 허용)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='현재 단가')),
                ('unit_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='주문 당시 단가 스냅샷')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='단위 (kg, box 등)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='요청사항')),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_registry.fishtype', verbose_name='어종 ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='주문 ID')),
            ],
            options={
                'verbose_name': '주문 품목',
                'verbose_name_plural': '주문 품목들',
                'db_table': 'order_items',
            },
        ),
    ]
