# Generated by Django 4.2.7 on 2025-09-01 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='주문 ID')),
                ('business_id', models.IntegerField(verbose_name='거래처 ID')),
                ('total_price', models.IntegerField(default=0, verbose_name='총 주문 금액')),
                ('order_datetime', models.DateTimeField(auto_now_add=True, verbose_name='주문 등록 일시')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='주문 메모')),
                ('source_type', models.CharField(choices=[('manual', '수동'), ('voice', '음성'), ('text', '문자')], max_length=20, verbose_name='주문 방식')),
                ('raw_input_path', models.TextField(blank=True, null=True, verbose_name='원문 경로 (음성 mp3 또는 문자 원문)')),
                ('transcribed_text', models.TextField(blank=True, null=True, verbose_name='파싱된 텍스트')),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True, verbose_name='납기일')),
                ('ship_out_datetime', models.DateTimeField(blank=True, null=True, verbose_name='출고일')),
                ('order_status', models.CharField(choices=[('placed', '등록됨'), ('ready', '출고 준비'), ('delivered', '납품 완료'), ('cancelled', '취소됨')], default='placed', max_length=20, verbose_name='주문 상태')),
                ('cancel_reason', models.CharField(blank=True, choices=[('customer_request', '고객 요청'), ('stock_shortage', '재고 부족'), ('quality_issue', '품질 문제'), ('delivery_delay', '배송 지연'), ('price_dispute', '가격 분쟁'), ('other', '기타')], max_length=50, null=True, verbose_name='취소 사유')),
                ('cancel_reason_detail', models.TextField(blank=True, null=True, verbose_name='취소 사유 상세')),
                ('refund_reason', models.CharField(blank=True, choices=[('customer_request', '고객 요청'), ('product_defect', '상품 하자'), ('wrong_delivery', '잘못된 배송'), ('delivery_delay', '배송 지연'), ('price_error', '가격 오류'), ('duplicate_payment', '중복 결제'), ('other', '기타')], max_length=50, null=True, verbose_name='환불 사유')),
                ('refund_reason_detail', models.TextField(blank=True, null=True, verbose_name='환불 사유 상세')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='긴급 주문 여부')),
                ('has_stock_issues', models.BooleanField(default=False, verbose_name='재고 부족 여부')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문들',
                'db_table': 'orders',
                'ordering': ['-order_datetime'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='주문 품목 ID')),
                ('item_name_snapshot', models.TextField(blank=True, null=True, verbose_name='주문 당시 품목명 스냅샷')),
                ('quantity', models.FloatField(verbose_name='주문 수량 (소수 허용)')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='현재 단가')),
                ('unit_price_snapshot', models.IntegerField(blank=True, null=True, verbose_name='주문 당시 단가 스냅샷')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='단위 (kg, box 등)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='요청사항')),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_registry.fishtype', verbose_name='어종 ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='주문 ID')),
            ],
            options={
                'verbose_name': '주문 품목',
                'verbose_name_plural': '주문 품목들',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='문서 요청 ID')),
                ('document_type', models.CharField(choices=[('tax_invoice', '세금계산서'), ('cash_receipt', '현금영수증')], max_length=20, verbose_name='문서 타입')),
                ('receipt_type', models.CharField(blank=True, choices=[('individual', '개인'), ('business', '사업자')], max_length=20, null=True, verbose_name='영수증 타입 (현금영수증용)')),
                ('identifier', models.CharField(max_length=20, verbose_name='식별번호 (사업자등록번호 또는 휴대폰번호)')),
                ('special_request', models.TextField(blank=True, null=True, verbose_name='특별 요청사항')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='order.order', verbose_name='주문 ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '문서 발급 요청',
                'verbose_name_plural': '문서 발급 요청들',
                'db_table': 'document_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
