# Generated by Django 4.2.7 on 2025-08-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source_type',
            field=models.CharField(choices=[('text', '문자'), ('voice', '음성'), ('image', '이미지'), ('manual', '수동')], max_length=10),
        ),
    ]
