# Generated by Django 4.2.7 on 2025-08-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='주문 등록 일시'),
        ),
    ]
