# Generated by Django 4.2.7 on 2025-08-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason_detail',
            field=models.TextField(blank=True, null=True, verbose_name='취소 사유 상세'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason',
            field=models.CharField(blank=True, choices=[('customer_request', '고객 요청'), ('product_defect', '상품 하자'), ('wrong_delivery', '잘못된 배송'), ('delivery_delay', '배송 지연'), ('price_error', '가격 오류'), ('duplicate_payment', '중복 결제'), ('other', '기타')], max_length=50, null=True, verbose_name='환불 사유'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason_detail',
            field=models.TextField(blank=True, null=True, verbose_name='환불 사유 상세'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('customer_request', '고객 요청'), ('stock_shortage', '재고 부족'), ('quality_issue', '품질 문제'), ('delivery_delay', '배송 지연'), ('price_dispute', '가격 분쟁'), ('other', '기타')], max_length=50, null=True, verbose_name='취소 사유'),
        ),
    ]
