# Generated by Django 4.2.7 on 2025-08-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='business',
        ),
        migrations.AddField(
            model_name='order',
            name='business_id',
            field=models.IntegerField(default=1, verbose_name='거래처 ID'),
            preserve_default=False,
        ),
    ]
