# Generated by Django 4.2.7 on 2025-08-19 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_order_cancel_reason_detail_order_refund_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='문서 요청 ID')),
                ('document_type', models.CharField(choices=[('tax_invoice', '세금계산서'), ('cash_receipt', '현금영수증')], max_length=20, verbose_name='문서 타입')),
                ('receipt_type', models.CharField(blank=True, choices=[('individual', '개인'), ('business', '사업자')], max_length=20, null=True, verbose_name='영수증 타입 (현금영수증용)')),
                ('identifier', models.CharField(max_length=20, verbose_name='식별번호 (사업자등록번호 또는 휴대폰번호)')),
                ('special_request', models.TextField(blank=True, null=True, verbose_name='특별 요청사항')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='order.order', verbose_name='주문 ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '문서 발급 요청',
                'verbose_name_plural': '문서 발급 요청들',
                'db_table': 'document_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
