# Generated by Django 4.2.7 on 2025-08-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_business_order_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_stock_issues',
            field=models.BooleanField(default=False, verbose_name='재고 부족 여부'),
        ),
    ]
