# Generated by Django 4.2.7 on 2025-08-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_documentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='현재 단가'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_snapshot',
            field=models.IntegerField(blank=True, null=True, verbose_name='주문 당시 단가 스냅샷'),
        ),
    ]
