# Generated by Django 4.2.7 on 2025-08-18 03:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTranscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(help_text='Uploaded audio file', upload_to='audio_files/%Y/%m/%d/')),
                ('transcription', models.TextField(blank=True, help_text='Transcribed text from the audio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed With Errors'), ('failed', 'Failed')], default='pending', help_text='Current status of the transcription process', max_length=25)),
                ('language', models.CharField(default='ko', help_text="Language code for transcription (e.g., 'ko' for Korean, 'en' for English)", max_length=10)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score of the transcription (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('create_order', models.BooleanField(default=False, help_text='Whether to create an order from this transcription')),
                ('business', models.ForeignKey(blank=True, help_text='Business this transcription is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriptions', to='business.business')),
                ('order', models.OneToOneField(blank=True, help_text='Order created from this transcription (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcription', to='order.order')),
                ('user', models.ForeignKey(help_text='User who uploaded the audio', on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='transcripti_status_599554_idx'), models.Index(fields=['created_at'], name='transcripti_created_2d6338_idx'), models.Index(fields=['user'], name='transcripti_user_id_4c0363_idx')],
            },
        ),
    ]
