# Generated by Django 4.2.7 on 2025-08-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='어종명')),
                ('aliases', models.TextField(blank=True, null=True, verbose_name='별칭')),
                ('scientific_name', models.TextField(blank=True, null=True, verbose_name='학명')),
                ('unit', models.CharField(max_length=10, verbose_name='단위')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
            ],
            options={
                'verbose_name': '어종',
                'verbose_name_plural': '어종 목록',
                'db_table': 'fish_types',
            },
        ),
    ]
