# Generated by Django 4.2.7 on 2025-08-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishtype',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='기본 단가'),
        ),
    ]
