# Generated by Django 4.2.7 on 2025-08-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_registry', '0002_fishtype_default_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishtype',
            name='default_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='기본 단가'),
        ),
    ]
