# Generated by Django 4.2.7 on 2025-08-08 05:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '거절됨'), ('suspended', '정지됨')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100, verbose_name='거래처명')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='전화번호는 9~12자리의 숫자여야 합니다.', regex='^\\d{9,12}$')], verbose_name='전화번호')),
                ('address', models.TextField(verbose_name='주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처들',
                'db_table': 'businesses',
            },
        ),
        # Set DEFAULT CURRENT_TIMESTAMP for datetime fields
        migrations.RunSQL(
            "ALTER TABLE users ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;",
            reverse_sql="ALTER TABLE users ALTER COLUMN created_at DROP DEFAULT;"
        ),
        migrations.RunSQL(
            "ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;",
            reverse_sql="ALTER TABLE users ALTER COLUMN updated_at DROP DEFAULT;"
        ),
        migrations.RunSQL(
            "ALTER TABLE businesses ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;",
            reverse_sql="ALTER TABLE businesses ALTER COLUMN created_at DROP DEFAULT;"
        ),
    ]
