# Generated by Django 4.2.7 on 2025-08-27 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RiskFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.BigIntegerField()),
                ('snapshot_date', models.DateField()),
                ('total_orders_30d', models.IntegerField()),
                ('unpaid_amount_30d', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_days_to_pay_90d', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('business_id', 'snapshot_date')},
                'index_together': {('snapshot_date',), ('business_id',)},
            },
        ),
    ]
