# Generated by Django 4.2.7 on 2025-08-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_user'),
    ]

    operations = [
        # Remove business_registration_number and subscription_plan from User model
        migrations.RemoveField(
            model_name='user',
            name='business_registration_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_plan',
        ),
    ]
