# Generated by Django 4.2.7 on 2025-08-15 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20250807_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_registration_number',
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='전화번호는 9~12자리의 숫자여야 합니다.', regex='^\\d{9,12}$')], verbose_name='전화번호'),
        ),
    ]
