# Generated by Django 4.2.7 on 2025-08-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_alter_order_user'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='결제 금액')),
                ('method', models.CharField(choices=[('cash', '현금'), ('bank_transfer', '계좌이체'), ('card', '카드')], max_length=20, verbose_name='결제 수단')),
                ('payment_status', models.CharField(choices=[('pending', '대기'), ('paid', '결제완료'), ('refunded', '환불됨')], default='pending', max_length=20, verbose_name='결제 상태')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제 완료 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='결제 등록 시각')),
                ('imp_uid', models.TextField(blank=True, null=True, verbose_name='PG사 결제 고유 ID')),
                ('merchant_uid', models.TextField(blank=True, null=True, verbose_name='시스템 결제 ID')),
                ('receipt_url', models.TextField(blank=True, null=True, verbose_name='발급된 영수증 URL')),
                ('card_approval_number', models.TextField(blank=True, null=True, verbose_name='카드 승인 번호')),
                ('bank_name', models.TextField(blank=True, null=True, verbose_name='은행명')),
                ('payer_name', models.TextField(blank=True, null=True, verbose_name='입금자명')),
                ('refunded', models.BooleanField(default=False, verbose_name='환불 여부')),
                ('refund_reason', models.TextField(blank=True, null=True, verbose_name='환불 사유')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business', verbose_name='거래처')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제들',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_requested', models.BooleanField(default=False, verbose_name='세금계산서 요청 여부')),
                ('is_issued', models.BooleanField(default=False, verbose_name='발급 여부')),
                ('invoice_number', models.TextField(blank=True, null=True, verbose_name='세금계산서 번호')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment', verbose_name='결제')),
            ],
            options={
                'verbose_name': '세금계산서',
                'verbose_name_plural': '세금계산서들',
                'db_table': 'tax_invoices',
            },
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_requested', models.BooleanField(default=False, verbose_name='현금영수증 요청 여부')),
                ('is_issued', models.BooleanField(default=False, verbose_name='발급 여부')),
                ('receipt_number', models.TextField(blank=True, null=True, verbose_name='현금영수증 번호')),
                ('receipt_contact', models.TextField(blank=True, null=True, verbose_name='전화번호 (개인용)')),
                ('business_number', models.TextField(blank=True, null=True, verbose_name='사업자 등록번호 (법인용)')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment', verbose_name='결제')),
            ],
            options={
                'verbose_name': '현금영수증',
                'verbose_name_plural': '현금영수증들',
                'db_table': 'cash_receipts',
            },
        ),
    ]
