# Generated by Django 4.2.7 on 2025-08-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인일시'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '거절됨'), ('suspended', '일시정지')], default='pending', max_length=20, verbose_name='계정 상태'),
        ),
    ]
